# Generated by Django 5.2.4 on 2025-07-18 09:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('gratuit', 'Période Gratuite'), ('attente_validation', 'En attente de validation'), ('actif', 'Actif'), ('refusé', 'Refusé'), ('expiré', 'Expiré')], default='gratuit', max_length=20)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=datetime.datetime(2025, 8, 17, 9, 19, 24, 927173, tzinfo=datetime.timezone.utc))),
                ('is_online_payment', models.BooleanField(default=False)),
                ('chargily_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
