# Generated by Django 5.2.4 on 2025-07-18 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='chargily_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 17, 15, 45, 23, 546374, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('gratuit', 'مجاني'), ('attente_validation', 'في انتظار التحقق'), ('actif', 'نشط'), ('refusé', 'مرفوض'), ('expiré', 'منتهي')], default='gratuit', max_length=20),
        ),
    ]
