# Generated by Django 5.2.4 on 2025-07-20 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_chargily_checkout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 19, 10, 2, 40, 217401, tzinfo=datetime.timezone.utc)),
        ),
    ]
