# Generated by Django 5.2.4 on 2025-07-20 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 19, 10, 30, 19, 813008, tzinfo=datetime.timezone.utc)),
        ),
    ]
