# Generated by Django 5.2.4 on 2025-07-20 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 19, 14, 1, 56, 388050, tzinfo=datetime.timezone.utc)),
        ),
    ]
