# Generated by Django 5.2.4 on 2025-07-22 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 21, 9, 8, 0, 96114, tzinfo=datetime.timezone.utc)),
        ),
    ]
