# Generated by Django 5.2.4 on 2025-07-29 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 28, 16, 49, 21, 616086, tzinfo=datetime.timezone.utc)),
        ),
    ]
