# Generated by Django 5.2.4 on 2025-07-29 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 28, 17, 7, 1, 454607, tzinfo=datetime.timezone.utc)),
        ),
    ]
