# Generated by Django 5.2.4 on 2025-07-30 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='chargily_invoice_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='chargily_payment_link_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 29, 12, 52, 45, 84926, tzinfo=datetime.timezone.utc)),
        ),
    ]
