# Generated by Django 5.2.4 on 2025-09-22 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_remove_subscription_chargily_invoice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 22, 23, 21, 17, 918705, tzinfo=datetime.timezone.utc)),
        ),
    ]
