# Generated by Django 5.2.4 on 2025-08-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('issued_by', models.CharField(blank=True, max_length=255)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='Statistiques')),
                ('documents', models.FileField(blank=True, null=True, upload_to='producer_docs/', verbose_name='Documents')),
                ('certifications', models.ManyToManyField(blank=True, related_name='producers', to='producers.certification', verbose_name='Certifications')),
            ],
        ),
    ]
