# Generated by Django 5.2.4 on 2025-09-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/', verbose_name='Image du certificat'),
        ),
    ]
