# Generated by Django 5.2.4 on 2025-09-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0005_producerprofile_latitude_producerprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='is_editable',
            field=models.BooleanField(default=False, verbose_name='Modification activée'),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='is_editable',
            field=models.BooleanField(default=False, verbose_name='Modification activée'),
        ),
    ]
