# Generated by Django 5.2.4 on 2025-08-04 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('specific_fields', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desc_courte', models.CharField(blank=True, max_length=255, verbose_name='Description courte')),
                ('cle_min', models.CharField(blank=True, max_length=100, verbose_name='Clé minimum')),
                ('prix_indicatif', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix indicatif')),
                ('delai_production', models.CharField(blank=True, max_length=100, verbose_name='Délai de production')),
                ('fiche_tech', models.FileField(blank=True, null=True, upload_to='fiches_tech/', verbose_name='Fiche technique')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Images')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Vidéo')),
                ('est_pret', models.BooleanField(default=False, verbose_name='Est prêt')),
                ('desc_longue', models.TextField(blank=True, verbose_name='Description longue')),
                ('region_org', models.CharField(blank=True, max_length=100, verbose_name="Région d'origine")),
                ('langue_du_product', models.CharField(blank=True, max_length=50, verbose_name='Langue du produit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
